apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: education-platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  source:
    repoURL: git@harbor.mokryakov.local:platform/education-platform-deploy.git
    targetRevision: master
    path: charts/education-platform
    helm:
      valueFiles: [values.yaml]
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff: { duration: 10s, factor: 2, maxDuration: 2m }
