apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: education-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@harbor.mokryakov.local:platform/education-platform-deploy.git
    targetRevision: master
    path: argocd/applications
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
